const {
	EVENTBRITE_CLIENT_KEY,
	EVENTBRITE_API_KEY,
	EVENTBRITE_PRIVATE_TOKEN,
	EVENTBRITE_PUBLIC_TOKEN,
	EVENTBRITE_ORGANIZATION_ID,
} = process.env;

export const EventbriteKeys = {
	clientKey: EVENTBRITE_CLIENT_KEY,
	apiKey: EVENTBRITE_API_KEY,
	privateToken: EVENTBRITE_PRIVATE_TOKEN,
	publicToken: EVENTBRITE_PUBLIC_TOKEN,
	organizationId: EVENTBRITE_ORGANIZATION_ID,
};
